name: First-Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code in GitHub
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with: 
          java-version: '21'

      - name: Build with maven
        run: mvn clean package

      - name: Build Docker Image
        run: docker build -t myapp:${{github.sha}} .
